[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/netlify/functions/restaurant-app" 
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods ="POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"